language: cpp
compiler:
    - g++
before_install:
    - sudo apt install flex bison libwww-perl patch
script:
    - cd cbmc/src
    - make minisat2-download
    - make
    - cd ../../
    - mkdir build
    - cd build
    - cmake ..
    - make
