language: cpp
branches:
    only:
    - ci
compiler:
    - g++
before_install:
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get -y update
    - sudo apt-get -y install cmake
    - sudo apt-get -y upgrade
script:
    - cd cbmc/src 
    - make 
    - cd ../../
    - mkdir build
    - cd build
    - cmake ..
    - make